# Generated by Django 5.2.1 on 2025-05-29 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_photo1_car_photo2_car_photo3_car_photo4_and_more'),
        ('reestr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='marka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carmarka'),
        ),
    ]
