# Generated by Django 5.2.1 on 2025-05-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0003_remove_registry_marka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='timePOPL',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='timeSDPL',
        ),
    ]
