# Generated by Django 5.2.1 on 2025-05-31 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0004_remove_registry_timepopl_remove_registry_timesdpl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=None)),
            ],
            options={
                'verbose_name': 'Вид груза',
                'verbose_name_plural': 'Виды груза',
            },
        ),
        migrations.AddField(
            model_name='registry',
            name='gruz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gruz_reestr', to='reestr.gruz'),
        ),
    ]
