# Generated by Django 5.2.1 on 2025-05-31 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_photo1_car_photo2_car_photo3_car_photo4_and_more'),
        ('pod', '0002_podryad_photo1_podryad_photo2_podryad_photo3_and_more'),
        ('reestr', '0005_gruz_registry_gruz'),
        ('vod', '0004_driver_vy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruz',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registry',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_registries', to='vod.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='driver2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_registries', to='vod.driver', verbose_name='Второй водитель'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='gruz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gruz_reestr', to='reestr.gruz', verbose_name='Вид груза'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='marsh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marsh_reestr', to='reestr.marsh', verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carnumber_reestr', to='car.car', verbose_name='Номер ТС'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='numberPL',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер ПЛ'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='pod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_reestr', to='pod.podryad', verbose_name='Подрядчик'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
