# Generated by Django 5.2.1 on 2025-06-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0006_alter_gruz_name_alter_registry_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Статус'),
        ),
    ]
