# Generated by Django 5.2.1 on 2025-09-10 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_alter_car_marka_alter_car_model'),
        ('pod', '0007_alter_podryad_cars'),
        ('reestr', '0007_alter_registry_status'),
        ('season', '0001_initial'),
        ('vod', '0010_remove_driver_contractor_remove_driver_photo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registries', to='season.season', verbose_name='Сезон'),
        ),
        migrations.AddIndex(
            model_name='registry',
            index=models.Index(fields=['dataPOPL'], name='reestr_regi_dataPOP_fc23f9_idx'),
        ),
        migrations.AddIndex(
            model_name='registry',
            index=models.Index(fields=['marsh'], name='reestr_regi_marsh_i_75fe70_idx'),
        ),
        migrations.AddIndex(
            model_name='registry',
            index=models.Index(fields=['pod'], name='reestr_regi_pod_id_60bc4b_idx'),
        ),
        migrations.AddIndex(
            model_name='registry',
            index=models.Index(fields=['season'], name='reestr_regi_season__e46969_idx'),
        ),
    ]
