# Generated by Django 5.2.1 on 2025-09-11 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0008_registry_season_and_more'),
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='season',
            field=models.ForeignKey(blank=True, default='-1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registries', to='season.season', verbose_name='Сезон'),
        ),
    ]
