# Generated by Django 5.2.1 on 2025-05-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podryad',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/podryad', verbose_name='Фото паспорта'),
        ),
        migrations.AddField(
            model_name='podryad',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/podryad', verbose_name='Фото паспорта, прописка'),
        ),
        migrations.AddField(
            model_name='podryad',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/podryad', verbose_name='Фото СНИЛСа'),
        ),
        migrations.AddField(
            model_name='podryad',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='photos/podryad', verbose_name='Фото ?'),
        ),
        migrations.AddField(
            model_name='podryad',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='photos/podryad', verbose_name='Фото ?'),
        ),
    ]
