# Generated by Django 5.2.1 on 2025-09-09 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod', '0003_podryad_user'),
        ('vod', '0010_remove_driver_contractor_remove_driver_photo1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podryad',
            options={'ordering': ['org_name'], 'verbose_name': 'Подрядчик', 'verbose_name_plural': 'Подрядчики'},
        ),
        migrations.RemoveField(
            model_name='podryad',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='podryad',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='podryad',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='podryad',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='podryad',
            name='photo5',
        ),
        migrations.AddField(
            model_name='podryad',
            name='adress',
            field=models.TextField(blank=True, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='podryad',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='contractors', to='vod.driver', verbose_name='Водители'),
        ),
        migrations.AddField(
            model_name='podryad',
            name='ogrn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='podryad',
            name='okpo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ОКПО'),
        ),
        migrations.CreateModel(
            name='PodryadPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/podryad_album/', verbose_name='Фото')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('podryad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pod.podryad', verbose_name='Подрядчик')),
            ],
            options={
                'verbose_name': 'Фотография подрядчика',
                'verbose_name_plural': 'Фотографии подрядчика',
            },
        ),
    ]
