# Generated by Django 5.2.1 on 2025-09-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod', '0004_alter_podryad_options_remove_podryad_photo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podryad',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер договора'),
        ),
    ]
