# Generated by Django 5.2.1 on 2025-09-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_remove_car_contractor'),
        ('pod', '0005_podryad_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='podryad',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='owners', to='car.car', verbose_name='Транспортные средства'),
        ),
    ]
