# Generated by Django 5.2.1 on 2025-09-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_remove_car_is_approved'),
        ('pod', '0006_podryad_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podryad',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='podryads', to='car.car', verbose_name='Транспортные средства'),
        ),
    ]
