# Generated by Django 5.2.1 on 2025-09-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod', '0008_podryad_approved_at_podryad_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podryad',
            name='refusal_reason',
            field=models.TextField(blank=True, help_text="Укажите причину, если статус 'Отклонено'", null=True, verbose_name='Причина отклонения'),
        ),
    ]
