# Generated by Django 5.2.1 on 2025-05-22 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMarka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Марка ТС')),
            ],
            options={
                'verbose_name': 'Марка ТС',
                'verbose_name_plural': 'Марка ТС',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Вид ТС')),
            ],
            options={
                'verbose_name': 'Вид ТС',
                'verbose_name_plural': 'Вид ТС',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Статус согласования')),
                ('number', models.CharField(max_length=20, verbose_name='Номер ТС')),
                ('sorka', models.CharField(max_length=20, verbose_name='Номер СОРКИ')),
                ('number_pr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер прицепа')),
                ('sorka_pr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер СОРКИ прицепа')),
                ('organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='pod.podryad', verbose_name='Организация')),
                ('marka', models.ForeignKey(help_text='Если нету в списке, то добавьте в разделе Марка ТС', on_delete=django.db.models.deletion.CASCADE, to='car.carmarka', verbose_name='Марка ТС')),
                ('model', models.ForeignKey(help_text='Если нету в списке, то добавьте в разделе Вид ТС', on_delete=django.db.models.deletion.CASCADE, to='car.carmodel', verbose_name='Вид ТС')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
    ]
