# Generated by Django 5.2.1 on 2025-05-22 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        ('pod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='marka',
            field=models.CharField(max_length=20, verbose_name='Марка ТС'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=20, verbose_name='Вид ТС'),
        ),
        migrations.AlterField(
            model_name='car',
            name='organization',
            field=models.ForeignKey(blank=True, default=195, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='pod.podryad', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='car',
            name='sorka',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер СОРКИ'),
        ),
        migrations.DeleteModel(
            name='CarMarka',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
