# Generated by Django 5.2.1 on 2025-05-22 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_marka_alter_car_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMarka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Марка ТС')),
            ],
            options={
                'verbose_name': 'Марка ТС',
                'verbose_name_plural': 'Марка ТС',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Вид ТС')),
            ],
            options={
                'verbose_name': 'Вид ТС',
                'verbose_name_plural': 'Вид ТС',
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='marka',
            field=models.ForeignKey(help_text='Если нету в списке, то добавьте в разделе Марка ТС', on_delete=django.db.models.deletion.CASCADE, to='car.carmarka', verbose_name='Марка ТС'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(help_text='Если нету в списке, то добавьте в разделе Вид ТС', on_delete=django.db.models.deletion.CASCADE, to='car.carmodel', verbose_name='Вид ТС'),
        ),
    ]
