# Generated by Django 5.2.1 on 2025-05-23 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_carmarka_carmodel_alter_car_marka_alter_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/drivers/', verbose_name='Фото ТС'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/drivers/', verbose_name='Фото СОРКИ спереди'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/drivers/', verbose_name='Фото СОРКИ сзади'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='photos/drivers/', verbose_name='Фото СОРКИ прицепа спереди'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='photos/drivers/', verbose_name='Фото СОРКИ прицепа сзади'),
        ),
        migrations.AlterField(
            model_name='car',
            name='marka',
            field=models.ForeignKey(help_text='Если нету в списке, то добавьте в разделе Марка ТС', on_delete=django.db.models.deletion.CASCADE, related_name='marka', to='car.carmarka', verbose_name='Марка ТС'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(help_text='Если нету в списке, то добавьте в разделе Вид ТС', on_delete=django.db.models.deletion.CASCADE, related_name='model', to='car.carmodel', verbose_name='Вид ТС'),
        ),
    ]
