# Generated by Django 5.2.1 on 2025-06-20 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_photo1_car_photo2_car_photo3_car_photo4_and_more'),
        ('pod', '0002_podryad_photo1_podryad_photo2_podryad_photo3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='organization',
        ),
        migrations.AddField(
            model_name='car',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='pod.podryad', verbose_name='Подрядчик'),
        ),
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер ТС'),
        ),
    ]
