# Generated by Django 5.2.1 on 2025-07-22 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_car_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
    ]
