# Generated by Django 5.2.1 on 2025-09-09 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_remove_car_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['number'], 'verbose_name': 'Транспортное средство', 'verbose_name_plural': 'Транспортные средства'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo5',
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/car_album/', verbose_name='Фото')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='car.car', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Фотография ТС',
                'verbose_name_plural': 'Фотографии ТС',
            },
        ),
    ]
