# Generated by Django 5.2.1 on 2025-09-09 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_car_options_remove_car_photo1_and_more'),
        ('pod', '0005_podryad_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='pod.podryad', verbose_name='Владелец (Подрядчик)'),
        ),
    ]
