# Generated by Django 5.2.1 on 2025-09-09 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_remove_car_contractor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_approved',
        ),
    ]
