# Generated by Django 5.2.1 on 2025-09-10 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_remove_car_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='marka',
            field=models.ForeignKey(help_text='Если нету в списке, то добавьте в разделе Марка ТС', on_delete=django.db.models.deletion.CASCADE, related_name='cars_by_marka', to='car.carmarka', verbose_name='Марка ТС'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(help_text='Если нету в списке, то добавьте в разделе Вид ТС', on_delete=django.db.models.deletion.CASCADE, related_name='cars_by_model', to='car.carmodel', verbose_name='Вид ТС'),
        ),
    ]
