# Generated by Django 5.2.1 on 2025-09-27 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_alter_car_marka_alter_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_by_marka', to='car.carmarka', verbose_name='Марка ТС'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_by_model', to='car.carmodel', verbose_name='Вид ТС'),
        ),
    ]
