# Generated by Django 5.2.1 on 2025-09-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название сезона')),
                ('date_start', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
                'ordering': ['-date_start', 'name'],
            },
        ),
    ]
