# Generated by Django 5.2.1 on 2025-05-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='snils',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='СНИЛС'),
        ),
    ]
