# Generated by Django 5.2.1 on 2025-05-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_photo1_car_photo2_car_photo3_car_photo4_and_more'),
        ('vod', '0002_alter_driver_snils'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/drivers/', verbose_name='Фото водителя'),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/drivers/', verbose_name='Фото ВУ спереди'),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo21',
            field=models.ImageField(blank=True, null=True, upload_to='photos/drivers/', verbose_name='Фото ВУ сзади'),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/drivers/', verbose_name='Фото СНИЛСА'),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='photos/drivers/', verbose_name='Фото Паспорта'),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='photos/drivers/', verbose_name='Фото Паспорта, прописка'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='drivers', to='car.car', verbose_name='Закрепленные ТС'),
        ),
    ]
