# Generated by Django 5.2.1 on 2025-05-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0003_driver_photo1_driver_photo2_driver_photo21_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vy_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи ВУ'),
        ),
    ]
