# Generated by Django 5.2.1 on 2025-06-20 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod', '0002_podryad_photo1_podryad_photo2_podryad_photo3_and_more'),
        ('vod', '0004_driver_vy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='pod.podryad', verbose_name='Подрядчик'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='full_name',
            field=models.CharField(default=1, help_text='ФИО Полностью', max_length=255, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
