# Generated by Django 5.2.1 on 2025-07-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0006_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='can_login',
            field=models.BooleanField(default=False, verbose_name='Доступ к личному кабинету'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Статус согласования СБ'),
        ),
    ]
