# Generated by Django 5.2.1 on 2025-08-05 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_remove_car_user'),
        ('vod', '0007_driver_can_login_alter_driver_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='cars',
        ),
        migrations.AddField(
            model_name='driver',
            name='assigned_car',
            field=models.ForeignKey(blank=True, help_text='Выберите закрепленное транспортное средство', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='car.car', verbose_name='Закрепленное ТС'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='can_login',
            field=models.BooleanField(default=True, verbose_name='Доступ к личному кабинету'),
        ),
    ]
