# Generated by Django 5.2.1 on 2025-08-05 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0008_remove_driver_cars_driver_assigned_car_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='assigned_car',
            new_name='cars',
        ),
    ]
