# Generated by Django 5.2.1 on 2025-09-09 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_car_options_remove_car_photo1_and_more'),
        ('vod', '0009_rename_assigned_car_driver_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='photo21',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='photo5',
        ),
        migrations.AddField(
            model_name='driver',
            name='dopog',
            field=models.BooleanField(default=False, verbose_name='Наличие ДОПОГа'),
        ),
        migrations.RemoveField(
            model_name='driver',
            name='cars',
        ),
        migrations.CreateModel(
            name='DriverPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/driver_album/', verbose_name='Фото')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vod.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Фотография водителя',
                'verbose_name_plural': 'Фотографии водителя',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='cars',
            field=models.ManyToManyField(blank=True, help_text='Выберите закрепленные транспортные средства', related_name='drivers', to='car.car', verbose_name='Закрепленные ТС'),
        ),
    ]
