# Generated by Django 5.2.1 on 2025-09-11 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0010_remove_driver_contractor_remove_driver_photo1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Одобрено когда'),
        ),
        migrations.AddField(
            model_name='driver',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drivers', to=settings.AUTH_USER_MODEL, verbose_name='Одобрено кем'),
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
