# Generated by Django 5.2.1 on 2025-09-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0011_driver_approved_at_driver_approved_by_driver_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='can_login',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='driver',
            name='refusal_reason',
            field=models.TextField(blank=True, help_text="Укажите причину, если статус 'Отклонено'", null=True, verbose_name='Причина отклонения'),
        ),
    ]
